# Generated by Django 4.1.7 on 2023-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('EmployeeAddress', models.CharField(max_length=500)),
                ('DOJ', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpPersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_contact', models.IntegerField()),
                ('S_contact', models.IntegerField(blank=True)),
            ],
        ),
    ]
